// Code generated by zek; DO NOT EDIT.

package types

import "encoding/xml"

// CartridgeBasicltiLink was generated 2022-05-10 19:56:34 by pierre on archpierre.
type CartridgeBasicltiLink struct {
	XMLName        xml.Name `xml:"cartridge_basiclti_link"`
	Text           string   `xml:",chardata"`
	Xmlns          string   `xml:"xmlns,attr"`
	Blti           string   `xml:"blti,attr"`
	Lticm          string   `xml:"lticm,attr"`
	Lticp          string   `xml:"lticp,attr"`
	Xsi            string   `xml:"xsi,attr"`
	SchemaLocation string   `xml:"schemaLocation,attr"`
	Title          string   `xml:"title"`
	Description    string   `xml:"description"`
	Custom         struct {
		Text     string `xml:",chardata"`
		Property struct {
			Text string `xml:",chardata"`
			Name string `xml:"name,attr"`
		} `xml:"property"`
	} `xml:"custom"`
	Extensions struct {
		Text     string `xml:",chardata"`
		Platform string `xml:"platform,attr"`
		Property struct {
			Text string `xml:",chardata"`
			Name string `xml:"name,attr"`
		} `xml:"property"`
	} `xml:"extensions"`
	LaunchURL       string `xml:"launch_url"`
	SecureLaunchURL string `xml:"secure_launch_url"`
	Icon            string `xml:"icon"`
	SecureIcon      string `xml:"secure_icon"`
	Vendor          struct {
		Text        string `xml:",chardata"`
		Code        string `xml:"code"`
		Name        string `xml:"name"`
		Description string `xml:"description"`
		URL         string `xml:"url"`
		Contact     struct {
			Text  string `xml:",chardata"`
			Email string `xml:"email"`
		} `xml:"contact"`
	} `xml:"vendor"`
	CartridgeBundle struct {
		Text          string `xml:",chardata"`
		Identifierref string `xml:"identifierref,attr"`
	} `xml:"cartridge_bundle"`
	CartridgeIcon struct {
		Text          string `xml:",chardata"`
		Identifierref string `xml:"identifierref,attr"`
	} `xml:"cartridge_icon"`
}
