// Code generated by zek; DO NOT EDIT.

package types

import "encoding/xml"

// Resource was generated 2022-05-10 19:56:34 by pierre on archpierre.
type Resource struct {
	XMLName     xml.Name `xml:"resource"`
	Text        string   `xml:",chardata"`
	Identifier  string   `xml:"identifier,attr"`
	Type        string   `xml:"type,attr"`
	Href        string   `xml:"href,attr"`
	Intendeduse string   `xml:"intendeduse,attr"`
	Metadata    struct {
		Text string `xml:",chardata"`
		Lom  struct {
			Text        string `xml:",chardata"`
			Educational struct {
				Text                string `xml:",chardata"`
				IntendedEndUserRole struct {
					Text   string `xml:",chardata"`
					Source string `xml:"source"`
					Value  string `xml:"value"`
				} `xml:"intendedEndUserRole"`
			} `xml:"educational"`
		} `xml:"lom"`
	} `xml:"metadata"`
	File []struct {
		Text string `xml:",chardata"`
		Href string `xml:"href,attr"`
	} `xml:"file"`
	Variant struct {
		Text          string `xml:",chardata"`
		Identifier    string `xml:"identifier,attr"`
		Identifierref string `xml:"identifierref,attr"`
		Metadata      string `xml:"metadata"`
	} `xml:"variant"`
	Dependency []struct {
		Text          string `xml:",chardata"`
		Identifierref string `xml:"identifierref,attr"`
	} `xml:"dependency"`
}
