// Code generated by zek; DO NOT EDIT.

package types

import "encoding/xml"

// Manifest was generated 2022-05-10 19:56:34 by pierre on archpierre.
type Manifest struct {
	XMLName        xml.Name `xml:"manifest"`
	Text           string   `xml:",chardata"`
	Identifier     string   `xml:"identifier,attr"`
	Xmlns          string   `xml:"xmlns,attr"`
	Lom            string   `xml:"lom,attr"`
	Lomimscc       string   `xml:"lomimscc,attr"`
	Xsi            string   `xml:"xsi,attr"`
	SchemaLocation string   `xml:"schemaLocation,attr"`
	Metadata       struct {
		Text          string `xml:",chardata"`
		Schema        string `xml:"schema"`
		Schemaversion string `xml:"schemaversion"`
		Lom           struct {
			Text    string `xml:",chardata"`
			General struct {
				Text  string `xml:",chardata"`
				Title struct {
					Text   string `xml:",chardata"`
					String struct {
						Text     string `xml:",chardata"`
						Language string `xml:"language,attr"`
					} `xml:"string"`
				} `xml:"title"`
				Language    string `xml:"language"`
				Description struct {
					Text   string `xml:",chardata"`
					String struct {
						Text     string `xml:",chardata"`
						Language string `xml:"language,attr"`
					} `xml:"string"`
				} `xml:"description"`
				Keyword struct {
					Text   string `xml:",chardata"`
					String struct {
						Text     string `xml:",chardata"`
						Language string `xml:"language,attr"`
					} `xml:"string"`
				} `xml:"keyword"`
			} `xml:"general"`
			LifeCycle struct {
				Text       string `xml:",chardata"`
				Contribute struct {
					Text string `xml:",chardata"`
					Date struct {
						Text     string `xml:",chardata"`
						DateTime string `xml:"dateTime"`
					} `xml:"date"`
					Entity struct {
						Text   string `xml:",chardata"`
						String string `xml:"string"`
					} `xml:"entity"`
					Role struct {
						Text   string `xml:",chardata"`
						String string `xml:"string"`
					} `xml:"role"`
				} `xml:"contribute"`
			} `xml:"lifeCycle"`
			Rights struct {
				Text                          string `xml:",chardata"`
				CopyrightAndOtherRestrictions struct {
					Text  string `xml:",chardata"`
					Value string `xml:"value"`
				} `xml:"copyrightAndOtherRestrictions"`
				Description struct {
					Text   string `xml:",chardata"`
					String string `xml:"string"`
				} `xml:"description"`
			} `xml:"rights"`
		} `xml:"lom"`
	} `xml:"metadata"`
	Organizations struct {
		Text         string `xml:",chardata"`
		Organization struct {
			Text       string `xml:",chardata"`
			Identifier string `xml:"identifier,attr"`
			Structure  string `xml:"structure,attr"`
			Item       Item   `xml:"item"`
		} `xml:"organization"`
	} `xml:"organizations"`
	Resources struct {
		Text     string     `xml:",chardata"`
		Resource []Resource `xml:"resource"`
	} `xml:"resources"`
}
