// Code generated by zek; DO NOT EDIT.

package types

import "encoding/xml"

// Item was generated 2022-05-10 19:56:34 by pierre on archpierre.
type Item struct {
	XMLName       xml.Name `xml:"item"`
	Text          string   `xml:",chardata"`
	Identifier    string   `xml:"identifier,attr"`
	Identifierref string   `xml:"identifierref,attr"`
	Title         string   `xml:"title"`
	Metadata      struct {
		Text string `xml:",chardata"`
		Lom  struct {
			Text    string `xml:",chardata"`
			General struct {
				Text      string `xml:",chardata"`
				Structure struct {
					Text   string `xml:",chardata"`
					Source string `xml:"source"`
					Value  string `xml:"value"`
				} `xml:"structure"`
			} `xml:"general"`
		} `xml:"lom"`
	} `xml:"metadata"`
	Item []Item `xml:"item"`
}
